version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: site-hyper-postgres
    restart: always
    environment:
      POSTGRES_DB: hyper
      POSTGRES_USER: hyperUser
      POSTGRES_PASSWORD: hyperPass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
