version: "3.1"
services:
  db:
    image: mysql:8.0
    container_name: somesound-database
    environment:
      - MYSQL_DATABASE=SomeSound
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
