spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    plataform: postgres
    url: jdbc:postgresql://localhost:5432/hyper
    username: hyperUser
    password: hyperPass
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    ignore-missing-migrations: false
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: undefined@gmail.com
#    password: undefined
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

stripe:
  webhook:
    secret: ${STRIPE_SECRET}
  secret:
    key: ${STRIPE_SECRET}
  checkout:
    success-url: "http://localhost:3000/payment/success?session_id={CHECKOUT_SESSION_ID}"
    cancel-url: "http://localhost:3000/payment/cancel"

api:
  security:
    token:
      secret: ${JWT_SECRET:lala}

server:
  port: 8080
