spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/SomeSound?useSSL=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
    baseline-on-migrate: true
    out-of-order: true
    ignore-missing-migrations: false

server:
  port: 8080
