spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    plataform: postgres
    url: jdbc:postgresql://localhost:5432/hyper
    username: hyperUser
    password: hyperPass
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: false
    baseline-on-migrate: true
    out-of-order: true
    ignore-missing-migrations: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: undefined@gmail.com
#    password: undefined
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

server:
  port: 8080
