spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
  datasource:
    plataform: postgres
    url: jdbc:postgresql://hyper-tst.cj8syw0omc8e.us-east-1.rds.amazonaws.com:5432/hyper
    username: hyperUser # Alterar
    password: hyperPass # Alterar
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    ignore-missing-migrations: false
  servlet:
    multipart:
      max-file-size: 120MB
      max-request-size: 120MB
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: undefined@gmail.com
#    password: undefined
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

stripe:
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET} # TODO
  secret:
    key: ${STRIPE_SECRET_KEY} # TODO
  checkout:
    success-url: "https://localhost:3000/success?session_id={CHECKOUT_SESSION_ID}" # TODO
    cancel-url: "https://localhost:3000/cancel" # TODO

api:
  security:
    token:
      secret: ${JWT_SECRET:lala}

server:
  port: 8080 # 443
