CREATE TABLE RECORDS (
	ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);
