CREATE TABLE COLLECTIONS (
	ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

ALTER TABLE COLLECTIONS ADD CONSTRAINT COLLECTION_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID);