CREATE TABLE TRACK_DOWNLOADS (
  ID BIGSERIAL PRIMARY KEY,
  CUSTOMER_ID UUID NOT NULL,
  TRACK_ID UUID NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE TRACK_PURCHASES ADD CONSTRAINT TRACK_DOWNLOADS_CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID);
ALTER TABLE TRACK_PURCHASES ADD CONSTRAINT TRACK_DOWNLOADS_TRACK_FK FOREIGN KEY (TRACK_ID) REFERENCES TRACKS(ID);
