CREATE TABLE ORDERS (
    ID BIGINT PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    TOTAL_ITEMS INTEGER NOT NULL,
    TOTAL_PRICE NUMERIC(38, 2),
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

ALTER TABLE ORDERS ADD CONSTRAINT ORDER_TABLE_CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID);