CREATE TABLE PLAYLIST_FOLLOWERS (
    CUSTOMER_ID  UUID NOT NULL,
    PLAYLIST_ID  UUID NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CUSTOMER_ID, PLAYLIST_ID)
);

ALTER TABLE PLAYLIST_FOLLOWERS ADD CONSTRAINT PLAYLIST_FOLLOWERS_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE RESTRICT;
ALTER TABLE PLAYLIST_FOLLOWERS ADD CONSTRAINT PLAYLIST_FOLLOWERS_PLAYLIST_ID_FK FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLISTS(ID) ON DELETE RESTRICT;