CREATE TABLE SUBSCRIPTIONS_HISTORY (
    ID BIGINT PRIMARY KEY,
    CUSTOMER_ID UUID    NOT NULL,
    SUBSCRIPTION_ID BIGINT NOT NULL,
    START_DATE DATE     NOT NULL,
    END_DATE DATE,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE SUBSCRIPTIONS_HISTORY ADD CONSTRAINT SUBSCRIPTIONS_HISTORY_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE RESTRICT;
ALTER TABLE SUBSCRIPTIONS_HISTORY ADD CONSTRAINT SUBSCRIPTIONS_HISTORY_SUBSCRIPTION_ID_FK FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES SUBSCRIPTIONS(ID) ON DELETE RESTRICT;