CREATE TABLE TRACK_ARTISTS (
    TRACK_ID UUID NOT NULL,
    ARTIST_ID UUID NOT NULL,
    ROLE VARCHAR(50),
    POSITION INTEGER DEFAULT 0,
    PRIMARY KEY (TRACK_ID, ARTIST_ID)
);

ALTER TABLE TRACK_ARTISTS ADD CONSTRAINT TRACK_ARTISTS_TRACK_ID_FK FOREIGN KEY (TRACK_ID) REFERENCES TRACKS(ID) ON DELETE RESTRICT;
ALTER TABLE TRACK_ARTISTS ADD CONSTRAINT TRACK_ARTISTS_ARTIST_ID_FK FOREIGN KEY (ARTIST_ID) REFERENCES ARTISTS(ID) ON DELETE RESTRICT;