CREATE TABLE TRACKS (
    ID UUID PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    RELEASE_ID UUID NOT NULL,
    GENRE VARCHAR(100) NOT NULL,
    COVER_URL VARCHAR(255) NOT NULL,
    FILE_URL VARCHAR(255) NOT NULL,
    DURATION INTEGER NOT NULL,
    PRICE FLOAT NOT NULL,
    ISRC VARCHAR(20) NOT NULL,
    TAGS VARCHAR(255) NOT NULL,
    PLAYS BIGINT NOT NULL,
    PRIVACY VARCHAR(20) NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

ALTER TABLE TRACKS ADD CONSTRAINT TRACKS_RELEASE_ID_FK FOREIGN KEY (RELEASE_ID) REFERENCES RELEASES(ID);