CREATE TABLE ARTISTS (
	ID BIGINT PRIMARY KEY,
    BIO VARCHAR(255),
    NAME VARCHAR(255) NOT NULL UNIQUE,
    CUSTOMER_ID BIGINT NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

CREATE SEQUENCE ARTISTS_SEQ START WITH 1;

ALTER TABLE ARTISTS ADD CONSTRAINT ARTISTS_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID);

