CREATE TABLE ARTISTS (
    ID UUID PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    IS_VERIFIED BOOLEAN NOT NULL
);

ALTER TABLE ARTISTS ADD CONSTRAINT FK_ARTIST_CUSTOMER FOREIGN KEY (ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE;
