CREATE TABLE RELEASES (
    ID UUID PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    OWNER UUID NOT NULL,
    IMAGE TEXT,
    UPC VARCHAR(50),
    RELEASE_DATE DATE,
    STATUS VARCHAR(50),
    DESCRIPTION VARCHAR(255) NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);
