CREATE TABLE LABEL_ARTISTS (
    LABEL_ID  UUID NOT NULL,
    ARTIST_ID  UUID NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (LABEL_ID, ARTIST_ID)
);

ALTER TABLE LABEL_ARTISTS ADD CONSTRAINT LABEL_ARTISTS_LABEL_ID_FK FOREIGN KEY (LABEL_ID) REFERENCES LABELS(ID) ON DELETE RESTRICT;
ALTER TABLE LABEL_ARTISTS ADD CONSTRAINT LABEL_ARTISTS_ARTIST_ID_FK FOREIGN KEY (ARTIST_ID) REFERENCES ARTISTS(ID) ON DELETE RESTRICT;