CREATE TABLE EMAIL (
    ID BIGINT PRIMARY KEY,
    OWNER VARCHAR(255) NOT NULL,
    EMAIL_FROM VARCHAR(255) NOT NULL,
    EMAIL_TO VARCHAR(255) NOT NULL,
    TEXT VARCHAR(255) NOT NULL,
    SEND_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    STATUS VARCHAR(255),
    SUBJECT VARCHAR(255),
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);