CREATE TABLE TRACK_PURCHASES (
  ID BIGSERIAL PRIMARY KEY,
  ARTIST_ID UUID NOT NULL,
  TRACK_ID UUID NOT NULL,
  AMOUNT DECIMAL(10,2) NOT NULL,
  PAYMENT_ID VARCHAR(255),
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE TRACK_PURCHASES ADD CONSTRAINT TRACK_PURCHASES_ARTIST_FK FOREIGN KEY (ARTIST_ID) REFERENCES ARTISTS(ID);
ALTER TABLE TRACK_PURCHASES ADD CONSTRAINT TRACK_PURCHASES_TRACK_FK FOREIGN KEY (TRACK_ID) REFERENCES TRACKS(ID);
