CREATE TABLE ROYALTIES (
    id BIGINT PRIMARY KEY,
    TRACK_ID BIGINT NOT NULL,
    SOURCE_DSP VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(10),
    STREAM_COUNT INTEGER DEFAULT 0,
    REVENUE_USD DECIMAL(10, 4) DEFAULT 0.0,
    REPORT_DATE DATE NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

ALTER TABLE ROYALTIES ADD CONSTRAINT ROYALTIES_TRACK_ID_FK FOREIGN KEY (TRACK_ID) REFERENCES TRACKS(ID);