CREATE TABLE PLAYLIST_COLABORATORS (
  PLAYLIST_ID UUID,
  CUSTOMER_ID UUID,
  PRIMARY KEY (PLAYLIST_ID, CUSTOMER_ID),
  FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLISTS(id),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(id)
);
