CREATE TABLE TRACKS (
    ID BIGINT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    RELEASE_ID BIGINT NOT NULL,
    GENRE VARCHAR(100) NOT NULL,
    FILE_URL VARCHAR(255) NOT NULL,
    DURATION TIME NOT NULL,
    PRICE FLOAT NOT NULL,
    ISRC VARCHAR(20) NOT NULL,
    EXPLICIT BOOLEAN DEFAULT FALSE,
    LANGUAGE VARCHAR(50),
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

ALTER TABLE TRACKS ADD CONSTRAINT TRACKS_RELEASE_ID_FK FOREIGN KEY (RELEASE_ID) REFERENCES RELEASES(ID);