CREATE TABLE FOLLOWS (
	ID BIGINT PRIMARY KEY,
    CUSTOMER BIGINT NOT NULL,
    FOLLOWING BIGINT NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

ALTER TABLE FOLLOWS ADD CONSTRAINT FOLLOW_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMERS(ID);
ALTER TABLE FOLLOWS ADD CONSTRAINT FOLLOW_FOLLOWING_ID_FK FOREIGN KEY (FOLLOWING) REFERENCES CUSTOMERS(ID);