CREATE TABLE CUSTOMER_FOLLOWERS (
    FOLLOWER_ID  UUID NOT NULL,
    FOLLOWEE_ID  UUID NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (FOLLOWER_ID, FOLLOWEE_ID)
);

ALTER TABLE CUSTOMER_FOLLOWERS ADD CONSTRAINT CUSTOMER_FOLLOWERS_FOLLOWER_ID_FK FOREIGN KEY (FOLLOWER_ID) REFERENCES CUSTOMERS(ID) ON DELETE RESTRICT;
ALTER TABLE CUSTOMER_FOLLOWERS ADD CONSTRAINT CUSTOMER_FOLLOWERS_FOLLOWEE_ID_FK FOREIGN KEY (FOLLOWEE_ID) REFERENCES CUSTOMERS(ID) ON DELETE RESTRICT;