CREATE TABLE RELEASES (
    id BIGSERIAL PRIMARY KEY,
    ARTIST_ID BIGINT NOT NULL REFERENCES artists(id) ON DELETE CASCADE,
    TITLE VARCHAR(255) NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    IMAGE_URL TEXT,
    UPC VARCHAR(50),
    RELEASE_DATE DATE,
    STATUS VARCHAR(50),
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

ALTER TABLE RELEASES ADD CONSTRAINT TRACK_RELEASE_ID_FK FOREIGN KEY (ARTIST_ID) REFERENCES ARTISTS(ID);
