CREATE TABLE ROYALTY_DISTRIBUTIONS (
    ID BIGINT PRIMARY KEY,
    ORDER_ITEM_ID BIGINT   NOT NULL,
    RECIPIENT_ID UUID      NOT NULL,
    ROLE VARCHAR(50),
    AMOUNT_USD DECIMAL(10,4) NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ROYALTY_DISTRIBUTIONS ADD CONSTRAINT ROYALTY_DISTRIBUTIONS_ORDER_ITEM_ID_FK FOREIGN KEY (ORDER_ITEM_ID) REFERENCES ORDER_ITEMS(ID) ON DELETE RESTRICT;
ALTER TABLE ROYALTY_DISTRIBUTIONS ADD CONSTRAINT ROYALTY_DISTRIBUTIONS_RECIPIENT_ID_FK FOREIGN KEY (RECIPIENT_ID) REFERENCES CUSTOMERS(ID) ON DELETE RESTRICT;