CREATE TABLE PLAYLISTS (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    CUSTOMER_ID BIGINT NOT NULL,
    COLLECTION_ID BIGINT,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

ALTER TABLE PLAYLISTS ADD CONSTRAINT PLAYLIST_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID);
ALTER TABLE PLAYLISTS ADD CONSTRAINT PLAYLIST_COLLECTION_ID_FK FOREIGN KEY (COLLECTION_ID) REFERENCES COLLECTIONS(ID);

