CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE CUSTOMERS (
	ID UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    COUNTRY VARCHAR(255) NOT NULL,
    BIRTH_DATE VARCHAR(255) NOT NULL,
    AVATAR_URL VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    ROLE SMALLINT CHECK (role BETWEEN 0 AND 2),
    SUBSCRIPTION_ID BIGINT NOT NULL DEFAULT 1,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

ALTER TABLE CUSTOMERS ADD CONSTRAINT CUSTOMERS_SUBSCRIPTION_ID_FK FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES SUBSCRIPTIONS(ID);