CREATE TABLE PLAY_HISTORY (
    ID BIGSERIAL PRIMARY KEY,
    TRACK_ID UUID NOT NULL,
    CUSTOMER_ID UUID,
    ANONYMOUS_SESSION_ID VARCHAR(255),
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE PLAY_HISTORY ADD CONSTRAINT PLAY_HISTORY_TRACK_FK FOREIGN KEY (TRACK_ID) REFERENCES TRACKS(ID);
ALTER TABLE PLAY_HISTORY ADD CONSTRAINT PLAY_HISTORY_CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID);
