CREATE TABLE TRACK_ARTISTS (
    TRACK_ID UUID NOT NULL,
    ARTIST_ID UUID NOT NULL,
    role VARCHAR(50),
    position INTEGER DEFAULT 0,
    PRIMARY KEY (TRACK_ID, ARTIST_ID),
    FOREIGN KEY (TRACK_ID) REFERENCES TRACKS(id),
    FOREIGN KEY (ARTIST_ID) REFERENCES ARTISTS(id)
);
