CREATE TABLE REVIEWS (
    ID BIGINT PRIMARY KEY,
    SCORE FLOAT NOT NULL,
	TRACK_ID BIGINT NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

ALTER TABLE REVIEWS ADD CONSTRAINT REVIEW_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID);
ALTER TABLE REVIEWS ADD CONSTRAINT REVIEW_TRACK_ID_FK FOREIGN KEY (TRACK_ID) REFERENCES TRACKS(ID);
