CREATE TABLE PLAYLIST_TRACK (
    PLAYLIST_ID UUID NOT NULL,
    TRACK_ID UUID NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PLAYLIST_ID, TRACK_ID),
    FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLISTS(ID),
    FOREIGN KEY (TRACK_ID) REFERENCES TRACKS(ID)
);
