CREATE TABLE SUBSCRIPTIONS (
    ID SERIAL PRIMARY KEY,
    TYPE VARCHAR(20) UNIQUE NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT,
    MONTHLY_PRICE NUMERIC(38,2),
    FREE_TRACK_LIMIT INTEGER,
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP
);

INSERT INTO SUBSCRIPTIONS(TYPE, NAME, DESCRIPTION, MONTHLY_PRICE, CREATED_DATE, LAST_MODIFIED_DATE) VALUES
('FREE', 'Plano Gratuito', 'Ouça músicas com anúncios. Sem publicação de faixas.', 0.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('PREMIUM', 'Plano Premium', 'Ouça músicas sem anúncios. Sem publicação de faixas.', 4.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ARTIST', 'Plano Artista', 'Publique até 5 faixas gratuitamente. Recursos extras para criadores.', 9.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
