CREATE TABLE RELEASES (
    ID UUID PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    COVER_URL TEXT,
    UPC VARCHAR(50),
    RELEASE_DATE DATE,
    STATUS VARCHAR(50),
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);
