CREATE TABLE PLAYLIST (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    CUSTOMER_ID BIGINT NOT NULL,
    COLLECTION_ID BIGINT,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

CREATE SEQUENCE PLAYLIST_SEQ START WITH 1;

ALTER TABLE PLAYLIST ADD CONSTRAINT PLAYLIST_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID);
ALTER TABLE PLAYLIST ADD CONSTRAINT PLAYLIST_COLLECTION_ID_FK FOREIGN KEY (COLLECTION_ID) REFERENCES COLLECTION(ID);

