CREATE TABLE PLAYLISTS (
    ID UUID PRIMARY KEY,
    CUSTOMER_ID UUID NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    COVER_URL TEXT,
    DESCRIPTION VARCHAR(255),
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

ALTER TABLE PLAYLISTS ADD CONSTRAINT PLAYLISTS_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE RESTRICT;
