CREATE TABLE CART_ITEMS (
    CART_ID    UUID NOT NULL,
    TRACK_ID   UUID NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CART_ID, TRACK_ID)
);

ALTER TABLE CART_ITEMS ADD CONSTRAINT CART_ITEMS_CART_ID_FK FOREIGN KEY (CART_ID) REFERENCES CARTS(ID) ON DELETE RESTRICT;
ALTER TABLE CART_ITEMS ADD CONSTRAINT CART_ITEMS_TRACK_ID_FK FOREIGN KEY (TRACK_ID) REFERENCES TRACKS(ID) ON DELETE RESTRICT;