CREATE TABLE CARTS (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    TOTAL_PRICE DECIMAL(4,2) NOT NULL,
    TOTAL_ITEMS INTEGER NOT NULL,
	ARTIST BIGINT NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

ALTER TABLE CARTS ADD CONSTRAINT CART_ARTIST_ID_FK FOREIGN KEY (ARTIST) REFERENCES ARTISTS(ID);