CREATE TABLE PLAYLIST_TRACK (
    PLAYLIST_ID BIGINT NOT NULL,
    TRACK_ID BIGINT NOT NULL,
    PRIMARY KEY (PLAYLIST_ID, TRACK_ID),
    FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST(ID) ON DELETE CASCADE,
    FOREIGN KEY (TRACK_ID) REFERENCES TRACK(ID) ON DELETE CASCADE
);
