CREATE TABLE DISTRIBUTION_REQUESTS (
    ID BIGINT PRIMARY KEY,
    RELEASE_ID UUID NOT NULL,
    TARGET_DPS JSONB NOT NULL,
    STATUS VARCHAR(50),
    SUBMITTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELIVERED_AT TIMESTAMP,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

ALTER TABLE DISTRIBUTION_REQUESTS ADD CONSTRAINT DISTRIBUTION_REQUESTS_RELEASE_ID_FK FOREIGN KEY (RELEASE_ID) REFERENCES RELEASES(ID);
