CREATE TABLE PLAYLIST_COLABORATORS (
  PLAYLIST_ID UUID,
  CUSTOMER_ID UUID,
  CREATED_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (PLAYLIST_ID, CUSTOMER_ID)
);

ALTER TABLE PLAYLIST_COLABORATORS ADD CONSTRAINT PLAYLIST_COLABORATORS_PLAYLIST_ID_FK FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLISTS(ID) ON DELETE RESTRICT;
ALTER TABLE PLAYLIST_COLABORATORS ADD CONSTRAINT PLAYLIST_COLABORATORS_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE RESTRICT;
