CREATE TABLE CUSTOMERS (
	ID UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    COUNTRY VARCHAR(255) NOT NULL,
    BIRTH_DATE VARCHAR(255) NOT NULL,
    COVER_URL TEXT,
    AVATAR_URL TEXT,
    BIOGRAPHY VARCHAR(255),
    ROLE VARCHAR(20) NOT NULL,
    SUBSCRIPTION_ID BIGINT NOT NULL DEFAULT 1,
    IS_ARTIST BOOLEAN NOT NULL DEFAULT FALSE,
    IS_LABEL BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

ALTER TABLE CUSTOMERS ADD CONSTRAINT CUSTOMERS_SUBSCRIPTION_ID_FK FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES SUBSCRIPTIONS(ID) ON DELETE RESTRICT;