CREATE TABLE LABELS (
	ID UUID PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    IS_VERIFIED BOOLEAN DEFAULT FALSE,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);