CREATE TABLE CARTS (
    ID UUID PRIMARY KEY,
    CUSTOMER_ID UUID    NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE CARTS ADD CONSTRAINT CARTS_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE RESTRICT;