CREATE TABLE PLAYLIST_TRACK (
    PLAYLIST_ID BIGINT NOT NULL,
    TRACK_ID BIGINT NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PLAYLIST_ID, TRACK_ID),
    FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLISTS(ID),
    FOREIGN KEY (TRACK_ID) REFERENCES TRACKS(ID)
);

ALTER TABLE PLAYLIST_TRACK ADD CONSTRAINT PLAYLIST_TRACK_PLAYLIST_ID_FK FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLISTS(ID);
ALTER TABLE PLAYLIST_TRACK ADD CONSTRAINT PLAYLIST_TRACK_TRACK_ID_FK FOREIGN KEY (TRACK_ID) REFERENCES TRACKS(ID);
