CREATE TABLE TRACK_GENRES (
    TRACK_ID UUID NOT NULL,
    GENRE_ID BIGINT NOT NULL,
    PRIMARY KEY (TRACK_ID, GENRE_ID)
);

ALTER TABLE TRACK_GENRES ADD CONSTRAINT TRACK_GENRES_TRACK_ID_FK FOREIGN KEY (TRACK_ID) REFERENCES TRACKS(ID) ON DELETE RESTRICT;
ALTER TABLE TRACK_GENRES ADD CONSTRAINT TRACK_GENRES_GENRE_ID_FK FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID) ON DELETE RESTRICT;