CREATE TABLE ORDER_ITEMS (
    ID BIGINT PRIMARY KEY,
    ORDER_ID UUID         NOT NULL,
    TRACK_ID UUID         NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ORDER_ITEMS ADD CONSTRAINT ORDER_ITEMS_ORDER_ID_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID) ON DELETE RESTRICT;
ALTER TABLE ORDER_ITEMS ADD CONSTRAINT ORDER_ITEMS_TRACK_ID_FK FOREIGN KEY (TRACK_ID) REFERENCES TRACKS(ID) ON DELETE RESTRICT;