CREATE TABLE CART_TRACK (
    CART_ID BIGINT NOT NULL,
    TRACK_ID BIGINT NOT NULL,
    PRIMARY KEY (cart_id, track_id),
    FOREIGN KEY (cart_id) REFERENCES cart(id) ON DELETE CASCADE,
    FOREIGN KEY (track_id) REFERENCES track(id) ON DELETE CASCADE
);