CREATE TABLE SUBSCRIPTIONS (
    ID BIGINT PRIMARY KEY,
    PLAN VARCHAR(255),
    PRICE NUMERIC(38,2),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP
);

INSERT INTO SUBSCRIPTIONS(ID, PLAN, PRICE, CREATED_DATE, LAST_MODIFIED_DATE) VALUES
(1, 'FREE', 0.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'SOLO', 4.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'COUPLE', 7.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'FAMILY', 14.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'ARTIST', 19.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'LABEL', 29.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);