CREATE TABLE CART_TRACK (
    CART_ID BIGINT NOT NULL,
    TRACK_ID BIGINT NOT NULL,
    PRIMARY KEY (CART_ID, TRACK_ID),
    FOREIGN KEY (CART_ID) REFERENCES CARTS(id) ON DELETE CASCADE,
    FOREIGN KEY (TRACK_ID) REFERENCES TRACKS(id) ON DELETE CASCADE
);