CREATE TABLE ARTISTS (
	ID UUID PRIMARY KEY,
    BIOGRAPHY VARCHAR(255),
    IS_VERIFIED BOOLEAN DEFAULT FALSE,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    CUSTOMER_ID UUID NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

ALTER TABLE ARTISTS ADD CONSTRAINT ARTISTS_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE RESTRICT;
