CREATE TABLE SUBSCRIPTION (
    ID BIGINT NOT NULL UNIQUE,
    _OPTION VARCHAR(255),
    PRICE NUMERIC(38,2),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP
);

CREATE SEQUENCE SUBSCRIPTION_SEQ START WITH 1;

ALTER TABLE SUBSCRIPTION ADD PRIMARY KEY (ID);

INSERT INTO SUBSCRIPTION(ID, _OPTION, PRICE, CREATED_DATE, LAST_MODIFIED_DATE) VALUES
(1, 'FREE', 0.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'SOLO', 4.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'COUPLE', 7.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'FAMILY', 14.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'ARTIST', 19.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'LABEL', 29.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);